global:
  scrape_interval: 1s

scrape_configs:
  - job_name: jobmanager
    static_configs:
      - targets: ['jobmanager:9091']

  - job_name: taskmanager
    static_configs:
      - targets: [ 'taskmanager:9091' ]