global:
  scrape_interval: 1s

scrape_configs:
  - job_name: jobmanager
    static_configs:
      - targets: ['jobmanager:9999']

  - job_name: taskmanager
    static_configs:
      - targets: [ 'taskmanager:9999' ]